### ISSUE TITLE
Docker run image procedure

### ISSUE THREAD

**Issue by waqas-mehmood-pk** [AminMkh/docker-php7-oci8-apache#1]
If you write the steps to run this image that will be very helpful for newbies like me. :) 
`How to run : `

`How to connect php: `

`How to connect with oracle db: `

when i run `docker run aminmkh/php7-apache-oci8` following message receives. 

![image](https://user-images.githubusercontent.com/9881496/39615984-8c4fbe44-4f92-11e8-9987-9d9cc8a855b5.png)

**Comment by Aminot1** [comment]
while I prefer to use docker-compose to run containers, you can still use docker cli to achieve the same thing.

to use with docker-compose

`docker-compose up`

That should build the image if it's not built, and also run it, you can just go to 
http/localhost/

and it should return the PHP info page, with OCI8 extension showing (installed and activated).

Regarding how to connect PHP with Oracle DB, you can check the [PHP documentation](http://php.net/manual/en/oci8.examples.php) if you are using vanilla PHP, I prefer to use a framework, which in that case you can look into the frameworks documentation on where to place the DB configurations, for instance, for Laravel I use [laravel-oci8 package](https://github.com/yajra/laravel-oci8)

I will try to add documentation to this repo :) thanks for pointing that out.

**Comment by clcneogeek325** [comment]
Hi guys, when I run docker-composer up, that show me the next error,
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20190902
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable multibyte string support... yes, shared
checking whether to enable multibyte regex support (requires oniguruma)... yes
checking for oniguruma... no
configure: error: Package requirements (oniguruma) were not met:

No package 'oniguruma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
ERROR: Service 'web' failed to build: The command '/bin/sh -c docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd     && docker-php-ext-configure mysqli --with-mysqli=mysqlnd     && docker-php-ext-install pdo_mysql     && docker-php-ext-install mbstring     && docker-php-ext-install mcrypt' returned a non-zero code: 1

**Comment by Aminot1** [comment]
@clcneogeek325 should be fixed
I set version to 7.1, it seemed the image isn't compatible with 7.2 or after. 
Will investigate / upgrade in the future.
